### ISSUE TITLE
Faz sentido que um estudante pesquise "2.1" e não "2.01"

### ISSUE THREAD

**Issue by jpcaveiro** [jpcaveiro/softboard#65]
- O mecanismo de pesquisa deve saber que 2.1 e 2.01 é o mesmo, ou então 
- O mecanismo de ordenar deve ter em conta esta falsidade do "ponto de vista do olho humano":
```{python}
>>> "1.10" < "1.5"
True
```

**Comment by fabiohfab** [comment]
@jpcaveiro O problema é que o título do exercício não é apenas o número dele mas sim "Ex. 1.01" o que torna mais difícil conseguir ordenar. Poderia implementar algo que fosse buscar apenas o número do exercício e ordenar por aí, mas caso algum exercício não tivesse número teríamos problemas.

Acho que o melhor será ter sempre o 1.01, etc... O mesmo se aplica a pesquisa do utilizador

Outra solução será termos um campo só com o número do exercício, mas implicaria ter que editar os que já estão inseridos. Se for para aplicar esta alteração, é melhor ser agora do que mais tarde quanto estiverem mais exercícios em bd

**Comment by jpcaveiro** [comment]
Vamos manter tudo como está nesta edição do softboard que é só uma
experiência.
Vou colocar "1.1" nas tags deixando o título do exercício em "Ex. 1.01" por
causa da ordem. A pesquisa é feita tb dentro das tags pelo que 1.1 vai
sempre ser encontrado.
Obrigado pela reflexão,
João Pedro






Fábio Henriques <notifications@github.com> escreveu no dia sábado,
29/02/2020 à(s) 11:11:
